import { User } from "./types";

const users: User[] = [
  {
    _id: "121",
    username: "iron_man",
    password: "stark123",
    name: "Tony Stark",
    email: "tony@stark.com",
    role: "user",
    following: ["125", "126", "127"],
  },
  {
    _id: "122",
    username: "dark_knight",
    password: "wayne123",
    name: "Bruce Wayne",
    email: "bruce@wayne.com",
    role: "user",
    following: ["121"],
  },
  {
    _id: "123",
    username: "capt_america",
    password: "rogers123",
    name: "Steve Rogers",
    email: "steve@avengers.com",
    role: "user",
    following: ["121"],
  },
  {
    _id: "124",
    username: "black_widow",
    password: "romanoff123",
    name: "Natasha Romanoff",
    email: "natasha@avengers.com",
    role: "user",
    following: ["121"],
  },
  {
    _id: "125",
    username: "thor_odinson",
    password: "mjolnir123",
    name: "Thor Odinson",
    email: "thor@asgard.com",
    role: "user",
    following: [],
  },
  {
    _id: "126",
    username: "hulk_smash",
    password: "banner123",
    name: "Bruce Banner",
    email: "bruce@avengers.com",
    role: "user",
    following: [],
  },
  {
    _id: "127",
    username: "ring_bearer",
    password: "shire123",
    name: "Frodo Baggins",
    email: "frodo@shire.com",
    role: "editor",
    following: [],
  },
  {
    _id: "128",
    username: "strider",
    password: "aragorn123",
    name: "Aragorn Elessar",
    email: "aragorn@gondor.com",
    role: "editor",
    following: [],
  },
  {
    _id: "129",
    username: "elf_archer",
    password: "legolas123",
    name: "Legolas Greenleaf",
    email: "legolas@mirkwood.com",
    role: "editor",
    following: [],
  },
];
export default users;
